name: Deploy to AWS S3 buckets (dev or prod)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Determine Target S3 Bucket
      id: set_bucket
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "::set-output name=bucket::${{ secrets.AWS_S3_BUCKET_DEV }}"
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "::set-output name=bucket::${{ secrets.AWS_S3_BUCKET_PROD }}"
        fi

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://${{ steps.set_bucket.outputs.bucket }} --exclude ".git/*" --exclude ".github/*" --delete
