---
name: Example Secrets Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use secret as environment variable
      run: echo "Secret is ${{ secrets.DATABASE_PASSWORD }}"